"XDG Directory Specification
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after
let g:netrw_home=$XDG_DATA_HOME.'/vim'

call plug#begin("$XDG_CONFIG_HOME/vim/plugged")
Plug 'ActivityWatch/aw-watcher-vim'
Plug 'hail2u/vim-css3-syntax'
Plug 'othree/html5.vim'
Plug 'sheerun/vim-polyglot'
Plug 'tmhedberg/matchit'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'valloric/matchtagalways'
Plug 'zethnest/ack.vim'
Plug 'vim-airline/vim-airline'
"Plug 'valloric/youcompleteme' " Slows startup-time
"Plug 'mg979/vim-visual-multi' " Unused

Plug 'airblade/vim-gitgutter'
let g:gitgutter_sign_added    = '●'
let g:gitgutter_sign_removed  = '●'
let g:gitgutter_sign_removed_above_and_below  = '●'
let g:gitgutter_sign_removed_first_line  = '●'
let g:gitgutter_sign_modified = '●'
let g:gitgutter_sign_modified_removed = '●'
highlight clear SignColumn
highlight GitGutterAdd    guifg=#009900 ctermfg=2 ctermbg=0
highlight GitGutterChange guifg=#bbbb00 ctermfg=3 ctermbg=0
highlight GitGutterDelete guifg=#ff2222 ctermfg=1 ctermbg=0
set signcolumn=yes
set updatetime=50

"Plug 'kien/ctrlp.vim' " In favor of fzf
"let g:ctrlp_map = ''
"let g:ctrlp_cmd = 'CtrlP'
"nnoremap <silent> <C-P> :CtrlPBuffer<CR>

let g:fzf_command_prefix = 'Fzf'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
let g:fzf_preview_window = []
nnoremap <silent> <C-P> :FzfBuffers<CR>
if executable('rg')
	let g:ackprg = 'rg --vimgrep'
elseif executable('ag')
	let g:ackprg = 'ag --vimgrep'
endif

Plug 'mattn/emmet-vim'
let g:user_emmet_leader_key = '\'
let g:user_emmet_install_global = 0
autocmd FileType html,css,php EmmetInstall

Plug 'dense-analysis/ale'
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
call plug#end()

let mapleader='\'

set undofile

set splitbelow
set splitright
set hidden

set diffopt+=vertical
set linebreak
set clipboard=unnamed
set backspace=indent,eol,start
set complete+=d
set grepprg=grep\ -rnsI
set incsearch
set mouse=a
set laststatus=2
set noswapfile
set shiftround
set tags=./tags;,tags;
set listchars=tab:░▒,trail:▓,space:∙,nbsp:,conceal:

set foldlevelstart=999
set foldmethod=indent

" set iskeyword=@,48-57,192-255 " originally @,48-57,_,192-255

set wildcharm=<C-z>
set wildmenu
set wildmode=full

set autoindent
set tabstop=4
set shiftwidth=0
set softtabstop=4
set smartindent

nnoremap <silent> ZW :set wrap!<CR>
nnoremap <silent> ZH :set list!<CR>
nnoremap <silent> Zh :set hlsearch!<CR>
nnoremap <silent> gb :b#<CR>

syntax on
filetype plugin on
filetype plugin indent on

autocmd BufReadPost * call AWStart()
